server:
  port: 9001

spring:
  #  application:
  #    name: ${demo01}
  datasource:
    #   时间格式错误默认值 zeroDateTimeBehavior=CONVERT_TO_NULL
    #   时区 serverTimezone=GMT%2B8（东八区）
    url: jdbc:mysql://localhost:3306/demo01?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    #   新版的驱动连接 com.mysql.cj.jdbc.Driver  （com.mysql.jdbc.Driver会报错）
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456

    # 连接池配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小、最小、最大
    initialSize: 10
    minIdle: 10
    maxActive: 20

# mybatis-plus配置官方文档 https://mp.baomidou.com/config/#typealiasessupertype
mybatis-plus:
  # Maven 多模块项目的扫描路径需以 classpath*: 开头 （即加载多个 jar 包下的 XML 文件）
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  type-aliases-package: com.shannon.sun.demo01.dal.entity
  # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。 default null
  type-aliases-super-type: java.lang.Object
  # 自动注入枚举
  type-enums-package: com.shannon.sun.demo01.dal.enums