server:
  port: 9001


spring:
  application:
    name: ${demo01}
  datasource:
    url: jdbc:mysql://localhost:3306/demo01?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456


# mybatis-plus配置官方文档 https://mp.baomidou.com/config/#typealiasessupertype
mybatis-plus:
# 指定外部化 MyBatis Properties 配置，通过该配置可以抽离配置，实现不同环境的配置部署。
  configuration-properties: classpath:mybatis/mybatis-config.yml