mybatis-plus:
#  mybatis配置文件路径
#  config-location: classpath:mybatis-config.xml

# Maven 多模块项目的扫描路径需以 classpath*: 开头 （即加载多个 jar 包下的 XML 文件）
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
# MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  type-aliases-package: com.shannon.sun.demo01.dal.entity
# 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。 default null
  type-aliases-super-type: java.lang.Object